steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/disco-beach-451611-h9/python-app-repo/python-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/disco-beach-451611-h9/python-app-repo/python-app']

# Deploy image to Cloud Run in a single line
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'python-app', '--image', 'us-central1-docker.pkg.dev/disco-beach-451611-h9/python-app-repo/python-app', '--region', 'us-central1']

images:
- 'us-central1-docker.pkg.dev/disco-beach-451611-h9/python-app-repo/python-app'

options:
  logging: CLOUD_LOGGING_ONLY
