apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: flask-python
build:
  artifacts:
    - image: gcr.io/my-python-project-451608/flask-python
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  cloudrun:
    projectid: my-python-project-451608
    region: us-central1
    container:
      name: flask-python-service
