name: Docker Image CI/CD to Cloud Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # Use self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin || exit 1

      - name: Build Docker Image
        run: |
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image-name"
          docker build -t $IMAGE_NAME:latest .
          docker save -o my-image.tar $IMAGE_NAME:latest

      - name: Upload Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-image.tar

  push:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: |
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image-name"
          docker load -i my-image.tar

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | gcloud auth activate-service-account --key-file=-
          gcloud auth configure-docker

      - name: Push Docker Image to GCR
        run: |
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image-name"
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

  deploy:
    runs-on: self-hosted
    needs: push

    steps:
      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | gcloud auth activate-service-account --key-file=-

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy my-cloud-run-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image-name:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
