name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🔹 Docker Hub Authentication (if using Docker Hub)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 🔹 Azure Container Registry (ACR) Authentication
      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # 🔹 GitHub Container Registry (GHCR) Authentication
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 🔹 Pull the Docker Image (Modify based on registry)
      - name: Pull Docker Image
        run: |
          docker pull myusername/myimagename:latest  # For Docker Hub
          docker pull ${{ secrets.ACR_LOGIN_SERVER }}/myimagename:latest  # For ACR
          docker pull ghcr.io/my-github-username/myimagename:latest  # For GHCR

      # 🔹 Run the Docker Container (Modify Ports if Needed)
      - name: Run Docker Container
        run: |
          docker run -d -p 80:80 myusername/myimagename:latest  # For Docker Hub
          docker run -d -p 80:80 ${{ secrets.ACR_LOGIN_SERVER }}/myimagename:latest  # For ACR
          docker run -d -p 80:80 ghcr.io/my-github-username/myimagename:latest  # For GHCR
