name: Python Action

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Use self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Build docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/python-flask"
          docker build -t $IMAGE_NAME:latest .
          docker save -o python-flask-image.tar $IMAGE_NAME:latest

      - name: upload docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: python-flask-image.tar

  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/my-image-name"
          docker load -i python-flask-image.tar

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/python-flask"
          docker push $IMAGE_NAME:latest


  deploy:
    runs-on: ubuntu-latest
    needs: push

    steps:
      - name: Authenticate with Google Cloud
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}' > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Google Cloud Run from Docker Hub
        run: |
          gcloud run deploy my-cloud-run-service \
            --image docker.io/${{ secrets.DOCKER_USERNAME }}/python-flask:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

