name: Docker Image CI/CD to Cloud Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted  # Use self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/my-image-name"
          docker build -t $IMAGE_NAME:latest .
          docker save -o my-image.tar $IMAGE_NAME:latest

      - name: Upload Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: my-image.tar

  push:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/my-image-name"
          docker load -i my-image.tar

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/my-image-name"
          docker push $IMAGE_NAME:latest

  deploy:
    runs-on: self-hosted
    needs: push

    steps:
      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | gcloud auth activate-service-account --key-file=-
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Google Cloud Run from Docker Hub
        run: |
          gcloud run deploy my-cloud-run-service \
            --image docker.io/${{ secrets.DOCKER_USERNAME }}/my-image-name:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
